@php
    $paysListe = [
        'Bénin',
        'Burkina Faso',
        "Côte d'Ivoire",
        'Guinée-Bissau',
        'Mali',
        'Niger',
        'Sénégal',
        'Togo',
        'Cap-Vert',
        'Gambie',
        'Ghana',
        'Guinée',
        'Libéria',
        'Nigeria',
        'Sierra Leone',
        'Cameroun',
        'Congo',
        'Gabon',
        'Guinée équatoriale',
        'République centrafricaine',
        'République démocratique du Congo',
        'Tchad',
        'Algérie',
        'Égypte',
        'Libye',
        'Maroc',
        'Mauritanie',
        'Soudan',
        'Tunisie',
        'Afrique du Sud',
        'Angola',
        'Burundi',
        'Comores',
        'Djibouti',
        'Érythrée',
        'Eswatini',
        'Éthiopie',
        'Kenya',
        'Lesotho',
        'Madagascar',
        'Malawi',
        'Maurice',
        'Mozambique',
        'Namibie',
        'Ouganda',
        'Rwanda',
        'Seychelles',
        'Somalie',
        'Soudan du Sud',
        'Tanzanie',
        'Zambie',
        'Zimbabwe',
        'Allemagne',
        'Autriche',
        'Belgique',
        'Bulgarie',
        'Chypre',
        'Croatie',
        'Danemark',
        'Espagne',
        'Estonie',
        'Finlande',
        'France',
        'Grèce',
        'Hongrie',
        'Irlande',
        'Islande',
        'Italie',
        'Lettonie',
        'Lituanie',
        'Luxembourg',
        'Malte',
        'Norvège',
        'Pays-Bas',
        'Pologne',
        'Portugal',
        'République tchèque',
        'Roumanie',
        'Royaume-Uni',
        'Russie',
        'Serbie',
        'Slovaquie',
        'Slovénie',
        'Suède',
        'Suisse',
        'Ukraine',
        'Arabie saoudite',
        'Bahreïn',
        'Chine',
        'Corée du Sud',
        'Émirats arabes unis',
        'Inde',
        'Indonésie',
        'Iran',
        'Irak',
        'Israël',
        'Japon',
        'Jordanie',
        'Koweït',
        'Liban',
        'Malaisie',
        'Oman',
        'Pakistan',
        'Philippines',
        'Qatar',
        'Singapour',
        'Syrie',
        'Thaïlande',
        'Turquie',
        'Viêt Nam',
        'Yémen',
        'Australie',
        'Nouvelle-Zélande',
        'Canada',
        'États-Unis',
        'Mexique',
        'Argentine',
        'Brésil',
        'Chili',
        'Colombie',
        'Équateur',
        'Pérou',
        'Uruguay',
        'Venezuela',
        'Autre',
    ];

    $selectedPays = $selectedPays ?? '';
@endphp

<option value="">-- Sélectionner --</option>
@foreach($paysListe as $paysOption)
    <option value="{{ $paysOption }}" @selected($selectedPays === $paysOption)>{{ $paysOption }}</option>
@endforeach
